#!/bin/bash

if [[ -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -f "${UCVM_INSTALL_PATH}/model/cs248/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/cs248/lib ./test_cs248
    exit
  fi
fi
env DYLD_LIBRARY_PATH=../src ./test_cs248

