name: cs248-ci

on:
  push:
    branches: [ foo ]

jobs:
  cs248-build-standalone-mac:
    if: false
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout cs248 main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: build cs248 
      run: ./.github/scripts/cs248-build.sh 
      shell: bash
    - name: test cs248 standalone
      run: ./.github/scripts/cs248-test-standalone.sh
      shell: bash

  cs248-build-standalone-linux:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout cs248 main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: build cs248
      run: ./.github/scripts/cs248-build.sh
      shell: bash
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 3000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cs248 standalone
      run: ./.github/scripts/cs248-test-standalone.sh
      shell: bash

